config/routes.rb
Mvp::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications
  
  resources :poll_options_sets

  root to: 'questions#index'

  resources :votes

  get 'polls/update_btns'
  resources :polls do
    resources :comments, only: [:create], :constraint => {:context_type => "polls"}
  end

  resources :responses

  get 'questions/reorder'
  resources :questions do
    resources :comments, only: [:create], :constraint => {:context_type => "questions"}
  end

  resources :officials

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :uq_relations, only: [:create, :update, :destroy]
  
  resources :up_relations, only: [:create, :update, :destroy]
  
  get 'up_relations/answer'
  get 'up_relations/result'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Question < ActiveRecord::Base
  attr_accessible :body, :title, :user, :up_cache, :down_cache, :rank_value, :controversy_value, :official_id

  belongs_to :official
  belongs_to :user

  has_many :questions, dependent: :destroy
  has_many :oq_relations, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :uq_relations, foreign_key: "user_id", dependent: :destroy
  has_many :voters, through: :uq_relations, source: :user
  has_many :comments, as: :commentable

  validates :user_id, presence: true
  validates :official_id, presence: true

  def calcRank
    if(updated_at != nil)
      time_val = Time.now - created_at
    else
      time_val = 10
    end

    up_down_value = up_cache - down_cache
    rank_value = 12/Math.log(time_val) + up_down_value
    update_attributes(:rank_value => rank_value)
  end

  def calcControversy
    if(updated_at != nil)
      time_val = Time.now - created_at
      if(up_cache == 0 and down_cache == 0)
        controversy_value = 0
      else
        cval = ((up_cache + down_cache + 10).to_f/((up_cache - down_cache).abs+9) - 1).abs
        controversy_value = 1/Math.log(time_val).abs + cval
      end
    else
      controversy_value = 0
    end

    update_attributes(:controversy_value => controversy_value)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :signed_in_user, only: [:create, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @comments = @question.comments.order("created_at DESC").paginate( :page => params[:page]||1,:per_page => 10)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end
  
  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # # POST /questions
  # # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question = current_user.questions.build(params[:question])
    @question.up_cache = 0
    @question.down_cache = 0
    @question.calcRank
    @question.calcControversy
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def reorder
    if (params[:state] == '1')
      @questionList = Question.order('rank_value DESC')
    elsif(params[:state] == '2')
      questions = Question.all
      @questionList = Question.order('controversy_value DESC')
    else
      @questionList = Question.order('created_at DESC')
    end

    respond_to do |format|
      format.html {}
      format.js { render "rebuildMain" }
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_changedownvote.html.erb
<%= form_for(current_user.uq_relations.find_by_question_id(question.id), html: {method: :put}, remote: true) do |f| %>
  <div><%= f.hidden_field :yaynay, value: false %></div>
  <%= f.submit "", type: :image, src: "/assets/images/arrows/down.gif", class: "imgButton" %>
<% end %>

app/views/questions/_changeupvote.html.erb
<%= form_for(current_user.uq_relations.find_by_question_id(question.id), html: {method: :put}, remote: true) do |f| %>
  <div><%= f.hidden_field :yaynay, value: true %></div>
  <%= f.submit "", type: :image, src: "/assets/images/arrows/up.gif", class: "imgButton" %>
<% end %>

app/views/questions/_downvote.html.erb
<%= form_for(current_user.uq_relations.build(question_id: question.id, yaynay: false, user_id: current_user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :question_id %></div>
  <div><%= f.hidden_field :yaynay %></div>
  <div><%= f.hidden_field :user_id %></div>
  <%= f.submit "", type: :image, src: "/assets/images/arrows/down.gif", class: "imgButton" %>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field q_form_title">
    <%= f.label "Question Title:"%>
    <%= f.text_field :title %>
  </div>
  <div class="field q_form_body">
    <%= f.label "Background:" %>
    <%= f.text_area( :body, :rows => 15) %>
  </div>
  <div class="field">
    <%= f.hidden_field :official_id, :value => @office.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<li>
  <span class="off_show_rating"><%= question.up_cache.to_i - question.down_cache.to_i %></span>
  <span class="title"><%= link_to question.title, question %></span>
  <span class="body"><%= question.body %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(question.created_at) %> ago.
  </span>
</li>


app/views/questions/_questionBlock.html.erb
<% questions.each do |question| %>

  <% @official = Official.find(question.official_id) %>
  <% if @official.district_id == 3 %>
    <div class="q_block index nat">
  <% elsif @official.district_id == 2 %>
    <div class="q_block index state">
  <% else %>
    <div class="q_block index city">
  <% end %>
    <div class="q_vote_form"><%= render 'vote_forms', question: question %></div>
    <div class="q_title"><%= link_to question.title, question %></div>
    <div class="q_body"><%= question.body %></div>
    <div class="q_asked_by">Asked by:  
      <%= link_to(User.find(question.user_id)) do %>
      <%= User.find(question.user_id).name %>
      <% end %>
      to
      <%= link_to(@official) do %>
      <%= @official.name %>
      <% end %>
      <fb:like href="http://polar-reaches-7121.herokuapp.com/questions/<%= question.id %>" send="true" width="450" show_faces="false"></fb:like>
    </div>
  </div>
<% end %>

app/views/questions/_showComments.js.erb
$("#comments").html("<%=escape_javascript(render :partial =>'comments/index',:locals => {:commentable=> @commentable,:comments => @commentable.comments.order('created_at DESC').paginate( :page => params[:page]||1,:per_page => 10)})%>");
$("#comment_content").val("")
$(".loading_pages").css("background", "none")

app/views/questions/_stats.html.erb
<div class="totals">
  <strong>
    <%= question.up_cache.to_i - question.down_cache.to_i %>
  </strong>
</div>

app/views/questions/_undodownvote.html.erb
<%= form_for(current_user.uq_relations.find_by_question_id(question.id), html: {method: :delete}, remote: true) do |f| %>
  <%= f.submit "", type: :image, src: "/assets/images/arrows/down-fill.gif", class: "imgButton" %>
<% end %>

app/views/questions/_undoupvote.html.erb
<%= form_for(current_user.uq_relations.find_by_question_id(question.id), html: {method: :delete},  remote: true) do |f| %>
  <%= f.submit "", type: :image, src: "/assets/images/arrows/up-fill.gif", class: "imgButton" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% if current_user %>

<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fapps.facebook.com%2Fasqus-mvp%2F&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=true&amp;font=arial&amp;colorscheme=light&amp;action=like&amp;height=80&amp;appId=264822796973610" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px; float:right;" allowTransparency="true"></iframe>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>

<div class="question_list">
<h1>Your Recent Questions</h1>

<div class="q_sort_menu">
  <%= link_to 'Sort by Ranking', questions_reorder_path(:state => 1), :remote => true, :class => "q_sort btn" %></br>
  <%= link_to 'Sort by Controversy', questions_reorder_path(:state => 2), :remote => true, :class => "q_sort btn" %></br>
  <%= link_to 'Sort by Most Recent', questions_reorder_path(:state => 3), :remote => true, :class => "q_sort btn" %>
</div>

<% questionList = Question.order('rank_value DESC') %>
<div id="questions">
  <%= render 'questionBlock', :questions => questionList %>
</div>



  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '264822796973610', // App ID
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });
    };

    // Load the SDK Asynchronously
    (function(d){
      var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
      js = d.createElement('script'); js.id = id; js.async = true;
      js.src = "//connect.facebook.net/en_US/all.js";
      d.getElementsByTagName('head')[0].appendChild(js);
    }(document));
  </script>

  


</div>
<div class="clear"></div>


<% else %>
<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
<% end %>

<p>Sign using one of these services:</p>
  <div class="social_sign_in">
  <a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %></a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %></a>
  </div>
  <div class="other_sign_in">
<p> Don't use these services? <p>
<%= link_to "Sign In", new_session_path %>
  </div>

  <div class="new_sign_in">
<p> New user? <p>
  <%= link_to "Sign Up", new_user_path %>
  </div>
  <br />
  </div>
<% end %>

app/views/questions/index.mobile.erb
<% if current_user %>



<% questionList = Question.order('rank_value DESC') %>

<div id="questions">
  <%= render 'questionBlock', :questions => questionList %>
</div>

<% else %>

<p>Sign using one of these services:</p>
  <div class="social_sign_in">
  <a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %></a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %></a>
  </div>
  <div class="other_sign_in">
<p> Don't use these services? <p>
<%= link_to "Sign In", new_session_path %>
  </div>

  <div class="new_sign_in">
<p> New user? <p>
  <%= link_to "Sign Up", new_user_path %>
  </div>
  <br />
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="row">
<div class="span7 q_form_block">
  <% if params[:office] %>
    <% @office = Official.find(params[:office]) %> 
    <h1>Ask <%= @office.name %>, <%= @office.position %>, a question</h1>
    <%= render 'form' %>
  <% else %>
    <h1>No rep selected!</h1>
  <% end %>
</div>
</div>