config/routes.rb
Mvp::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications
  
  resources :poll_options_sets

  root to: 'questions#index'

  resources :votes

  get 'polls/update_btns'
  resources :polls do
    resources :comments, only: [:create], :constraint => {:context_type => "polls"}
  end

  resources :responses

  get 'questions/reorder'
  resources :questions do
    resources :comments, only: [:create], :constraint => {:context_type => "questions"}
  end

  resources :officials

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :uq_relations, only: [:create, :update, :destroy]
  
  resources :up_relations, only: [:create, :update, :destroy]
  
  get 'up_relations/answer'
  get 'up_relations/result'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 

end

app/models/poll_options_set.rb
class PollOptionsSet < ActiveRecord::Base
  attr_accessible :num_options, :options, :set_type
end

app/controllers/poll_options_sets_controller.rb
class PollOptionsSetsController < ApplicationController
  # GET /poll_options_sets
  # GET /poll_options_sets.json
  def index
    @poll_options_sets = PollOptionsSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @poll_options_sets }
    end
  end

  # GET /poll_options_sets/1
  # GET /poll_options_sets/1.json
  def show
    @poll_options_set = PollOptionsSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll_options_set }
    end
  end

  # GET /poll_options_sets/new
  # GET /poll_options_sets/new.json
  def new
    @poll_options_set = PollOptionsSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll_options_set }
    end
  end

  # GET /poll_options_sets/1/edit
  def edit
    @poll_options_set = PollOptionsSet.find(params[:id])
  end

  # POST /poll_options_sets
  # POST /poll_options_sets.json
  def create
    @poll_options_set = PollOptionsSet.new(params[:pos])

    respond_to do |format|
      if @poll_options_set.save
        format.js { render "/polls/addOptionSet"}
      else
        format.html { render action: "new" }
        format.json { render json: @poll_options_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /poll_options_sets/1
  # PUT /poll_options_sets/1.json
  def update
    @poll_options_set = PollOptionsSet.find(params[:id])

    respond_to do |format|
      if @poll_options_set.update_attributes(params[:poll_options_set])
        format.html { redirect_to @poll_options_set, notice: 'Poll options set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll_options_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poll_options_sets/1
  # DELETE /poll_options_sets/1.json
  def destroy
    @poll_options_set = PollOptionsSet.find(params[:id])
    @poll_options_set.destroy

    respond_to do |format|
      format.html { redirect_to poll_options_sets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/poll_options_sets_helper.rb
module PollOptionsSetsHelper
end

app/views/poll_options_sets/_form.html.erb
<%= form_for(@poll_options_set) do |f| %>
  <% if @poll_options_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll_options_set.errors.count, "error") %> prohibited this poll_options_set from being saved:</h2>

      <ul>
      <% @poll_options_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_area :options %>
  </div>
  <div class="field">
    <%= f.label :set_type %><br />
    <%= f.text_field :set_type %>
  </div>
  <div class="field">
    <%= f.label :num_options %><br />
    <%= f.number_field :num_options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poll_options_sets/_new_partial.html.erb
<label>Set Type:</label>
<input id="set_type" /></br></br>
<div id="options_div">
  <label>Options:</label>
  <div id="select0" class="optionSelect">
    <input id="option0" class="options" />
    <div id="addOption" class="btn btn-primary" onclick="addOpt()">+</div>
    <div id="removeOption" class="btn btn-danger" onclick="removeOpt()">-</div>
  </div>
</div>
<div id="submit_pos" class="btn btn-primary" onclick="createPOS()">Save</div>
<div id="discard_pos" class="btn btn-danger" onclick="discardPOS()">Discard</div>

app/views/poll_options_sets/edit.html.erb
<h1>Editing poll_options_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll_options_set %> |
<%= link_to 'Back', poll_options_sets_path %>

app/views/poll_options_sets/index.html.erb
<h1>Listing poll_options_sets</h1>

<table>
  <tr>
    <th>Options</th>
    <th>Set type</th>
    <th>Num options</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @poll_options_sets.each do |poll_options_set| %>
  <tr>
    <td><%= poll_options_set.options %></td>
    <td><%= poll_options_set.set_type %></td>
    <td><%= poll_options_set.num_options %></td>
    <td><%= link_to 'Show', poll_options_set %></td>
    <td><%= link_to 'Edit', edit_poll_options_set_path(poll_options_set) %></td>
    <td><%= link_to 'Destroy', poll_options_set, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poll options set', new_poll_options_set_path %>

app/views/poll_options_sets/new.html.erb
<h1>New poll_options_set</h1>

<%= render 'form' %>

<%= link_to 'Back', poll_options_sets_path %>

app/views/poll_options_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Options:</b>
  <%= @poll_options_set.options %>
</p>

<p>
  <b>Set type:</b>
  <%= @poll_options_set.set_type %>
</p>

<p>
  <b>Num options:</b>
  <%= @poll_options_set.num_options %>
</p>


<%= link_to 'Edit', edit_poll_options_set_path(@poll_options_set) %> |
<%= link_to 'Back', poll_options_sets_path %>