config/routes.rb
Mvp::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications
  
  resources :poll_options_sets

  root to: 'questions#index'

  resources :votes

  get 'polls/update_btns'
  resources :polls do
    resources :comments, only: [:create], :constraint => {:context_type => "polls"}
  end

  resources :responses

  get 'questions/reorder'
  resources :questions do
    resources :comments, only: [:create], :constraint => {:context_type => "questions"}
  end

  resources :officials

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :uq_relations, only: [:create, :update, :destroy]
  
  resources :up_relations, only: [:create, :update, :destroy]
  
  get 'up_relations/answer'
  get 'up_relations/result'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
  	attr_accessible :user_id, :provider, :uid
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  attr_accessible :author, :content, :user_id
end

app/models/official.rb
# == Schema Information
#
# Table name: officials
#
#  id          :integer          not null, primary key
#  position    :string(255)
#  name        :string(255)
#  district_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Official < ActiveRecord::Base
  attr_accessible :district_id, :name, :position, :email

  has_many :users
  has_many :questions
  has_many :polls

end

app/models/poll.rb
# == Schema Information
#
# Table name: polls
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Poll < ActiveRecord::Base
  attr_accessible :body, :title, :user, :poll_options_set_id, :official_id

  belongs_to :official
  belongs_to :user

  # has_many :answers, dependent: :destroy
  has_many :up_relations, foreign_key: "user_id", dependent: :destroy
  has_many :voters, through: :up_relations, source: :user_id
  has_many :comments, as: :commentable
  
  validates :user_id, presence: true
  validates :official_id, presence: true

  default_scope order: 'polls.created_at DESC'

end

app/models/poll_options_set.rb
class PollOptionsSet < ActiveRecord::Base
  attr_accessible :num_options, :options, :set_type
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Question < ActiveRecord::Base
  attr_accessible :body, :title, :user, :up_cache, :down_cache, :rank_value, :controversy_value, :official_id

  belongs_to :official
  belongs_to :user

  has_many :questions, dependent: :destroy
  has_many :oq_relations, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :uq_relations, foreign_key: "user_id", dependent: :destroy
  has_many :voters, through: :uq_relations, source: :user
  has_many :comments, as: :commentable

  validates :user_id, presence: true
  validates :official_id, presence: true

  def calcRank
    if(updated_at != nil)
      time_val = Time.now - created_at
    else
      time_val = 10
    end

    up_down_value = up_cache - down_cache
    rank_value = 12/Math.log(time_val) + up_down_value
    update_attributes(:rank_value => rank_value)
  end

  def calcControversy
    if(updated_at != nil)
      time_val = Time.now - created_at
      if(up_cache == 0 and down_cache == 0)
        controversy_value = 0
      else
        cval = ((up_cache + down_cache + 10).to_f/((up_cache - down_cache).abs+9) - 1).abs
        controversy_value = 1/Math.log(time_val).abs + cval
      end
    else
      controversy_value = 0
    end

    update_attributes(:controversy_value => controversy_value)
  end
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id          :integer          not null, primary key
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :integer
#  user_id     :integer
#

class Response < ActiveRecord::Base
  attr_accessible :body

  belongs_to :user
  belongs_to :question

  validates :user_id, presence: true
  validates :question_id, presence: true
end

app/models/up_relation.rb
class UpRelation < ActiveRecord::Base
  attr_accessible :poll_id, :user_id, :updown, :answer_value

  belongs_to :poll, class_name: "Poll"
  belongs_to :user, class_name: "User"

  validates :poll_id, presence: true
  validates :user_id, presence: true
end

app/models/uq_relation.rb
class UqRelation < ActiveRecord::Base
  attr_accessible :question_id, :user_id, :yaynay

  belongs_to :question, class_name: "Question"
  belongs_to :user, class_name: "User"

  validates :question_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  birthdate  :date
#  email      :string(255)
#  address    :string(255)
#  password   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :address, :birthdate, :email, :name, :password, :password_confirmation, :official_id
  has_secure_password

  belongs_to  :official

  has_many :authentications
  has_many :responses
  has_many :questions, dependent: :destroy
  has_many :uq_relations, dependent: :destroy
  has_many :voted_questions, through: :uq_relations, source: :question
  has_many :up_relations, dependent: :destroy
  has_many :voted_polls, through: :up_relations, source: :poll
  has_many :polls

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true
  validates :email, presence: true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def didvoteQ?(question, yaynay)
    uqrel = uq_relations.find_or_create_by_user_id_and_question_id(id,question.id)
    if(uqrel.yaynay != yaynay)
      return false
    else
      return true
    end
  end

  def voteQ!(question,yaynay)
    uq_relations.create!(yaynay: yaynay, user_id: id, question_id: question.id)
  end


  def didvotepoll?(poll, updown)
    uprel = up_relations.find_or_create_by_user_id_and_poll_id(id,poll.id)
    if(uprel.updown != updown)
      return false
    else
      return true
    end
  end

  def votepoll!(poll, updown)
    up_relations.create!(updown: updown, user_id: id, poll_id: poll.id)
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  response   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ActiveRecord::Base
  attr_accessible :response
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/officials_helper.rb
module OfficialsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/uq_relations_helper.rb
module UqRelationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_footer.mobile.erb
<div data-role="footer">
  <div data-role="navbar">
    <ul>
      <li><%= link_to 'Officials', officials_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ul>
  </div>
</div>



app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav_logo">
        <%= link_to(root_path) do %>
          <div class="nav_logo_image">
          <%= image_tag "header_logo.png" %>
          </div>
          <% if signed_in? %>
            <% if current_user.official_id %>
              <div class="nav_logo_text">
                PDP Rep Interface
              </div>
            <% else %>
              <div class="nav_logo_text">
                Political Dialogue Platform
              </div>
            <% end %>
          <% else %>
            <div class="nav_logo_text">
              Political Dialogue Platform
            </div>
          <% end %>
        <% end %>
      </div>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Officials", officials_path %></li>
            <li><%= link_to "Questions", questions_path %></li>
            <li><%= link_to "Polls", polls_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b> </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <% if current_user.official_id %>
                  <li> <%= link_to "My Office", Official.find(current_user.official_id) %></li>
                  <li class="divider"></li>
                <% end %>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header.mobile.erb
  <div data-role="header" data-position="fixed" class="ui_header ui-bar-a" role="banner">
  <div data-role="navbar">
    <ul>
      <li>
          <%= link_to(root_path) do %>
              <%= image_tag "header_logo.png", :size=>"40x16" %>
         <% end %>
      </li>
          <% if signed_in? %>
            <li><%= link_to "Polls", polls_path %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
    </ul>
  </div><!-- /navbar --> 
  </div><!-- /header --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
  <title>Mvp</title>


  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= yield :head %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <%= render 'layouts/header' %>  
  <% if current_user %>
    <% if current_user.official_id %>
      <style>
        body {background-color: #D5FFC7}
      </style>
    <% end %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>

  <div id="u_picture"><%= image_tag "logo_corner.png" %></div>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
  <title>Mobile Political Dialogue Platform</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile.min" %>
  <%= stylesheet_link_tag "jquery.mobile.min.css" %>
  <%= csrf_meta_tags %>



</head>
<body>
<div data-role="page">  
  <%= render 'layouts/header.mobile.erb' %>  
    <%= yield %>
  <%= render 'layouts/footer.mobile.erb' %>  
</div>


</body>
</html>